[project]
name = "autumn"
version = "1.2.0"
description = "A thin wrapper around Autumn's REST API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.5",
    "requests>=2.32.3",
]

[project.optional-dependencies]
aio = [
    "aiohttp>=3.12.8",
]
asgi = [
    "starlette>=0.47.0",
    "aiohttp>=3.12.8"
]
docs = [
    "furo>=2024.8.6",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
    "sphinx-tabs>=3.4.7",
]
tests = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]
dev = [
    "litestar>=2.16.0",
    "uvicorn>=0.34.3",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
